apiVersion: v1
kind: ServiceAccount
metadata:
  name: github
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit
  namespace: default
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
subjects:
  - kind: ServiceAccount
    name: github
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  annotations:
    kubernetes.io/service-account.name: github
type: kubernetes.io/service-account-token

